version: '3'
services:
  weewx:
    build: .
    image: makobdk/weewx5:latest
    container_name: weewx
    environment:
      WEEWX_USER: ${USER}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /home/${USER}/weewx/passwd:/etc/passwd:ro
      - /home/${USER}/weewx/group:/etc/group:ro
      - /home/${USER}/weewx/archive:/home/weewx/archive
      - /home/${USER}/weewx/weewx.conf:/home/weewx/weewx.conf
      - /home/${USER}/.public_html:/home/weewx/public_html
      - /home/${USER}/.ssh:/home/weewx/.ssh
